services:
  - type: web
    name: antim-rupee-api
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt && python api/ingest.py && python api/engine.py"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
