import React, { useState } from 'react';
import { FileDown, Loader, Sparkles } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ProposalGenerator({ hotspotData }) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(41, 128, 185);
      doc.text("Antim Rupee Infrastructure Proposal", 14, 20);
      
      doc.setFontSize(11);
      doc.setTextColor(100);
      doc.text("Generated by Vertex AI & Gemini 3.5", 14, 28);
      
      doc.setDrawColor(200);
      doc.line(14, 32, 196, 32);
      
      // Project Details
      doc.setFontSize(16);
      doc.setTextColor(40);
      doc.text("Project: " + (hotspotData?.title || "Rural Water Pipeline Repair & Extension"), 14, 45);
      
      doc.setFontSize(12);
      doc.text("Location: " + (hotspotData?.location || "Ward 12, Muzaffarpur District, Bihar"), 14, 55);
      doc.text("Estimated Budget: ₹" + (hotspotData?.budget || "25,50,000"), 14, 62);
      doc.text("Verified Citizen Requests: " + (hotspotData?.requests || "342 (Aggregated from Voice/Text)"), 14, 69);
      doc.text("AI Priority Score: " + (hotspotData?.score || "94/100") + " (CRITICAL SEVERITY)", 14, 76);
      
      // Table
      autoTable(doc, {
        startY: 85,
        head: [['Demographic Marker', 'Value', 'Impact Factor']],
        body: [
          ['Directly Affected Population', '~4,500 residents', 'High'],
          ['Economic Vulnerability Index', '72.4 (High)', 'Medium-High'],
          ['Current Infrastructure Health', 'Severely Degraded', 'Critical'],
          ['Projected 10-year ROI', '3.2x (Health & Agri)', 'Excellent']
        ],
        theme: 'grid',
        headStyles: { fillColor: [67, 56, 202] }
      });
      
      // Summary
      doc.text("AI Synthesis & Recommendation:", 14, doc.lastAutoTable.finalY + 15);
      doc.setFontSize(11);
      doc.setTextColor(60);
      const splitText = doc.splitTextToSize(
        "Based on the consolidation of 342 independent citizen reports over the last 90 days, combined with satellite imagery analysis (Earth Engine) and demographic overlays, this project represents the highest ROI for infrastructure spending in the current quarter. Immediate tender allocation is recommended to prevent cascading water scarcity during the dry season.",
        180
      );
      doc.text(splitText, 14, doc.lastAutoTable.finalY + 22);
      
      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text("Antim Rupee - Empowering Citizens, Informing Policy", 14, 280);
      
      doc.save("Antim_Rupee_Impact_Proposal.pdf");
      setIsGenerating(false);
    }, 2500);
  };

  return (
    <button 
      onClick={generatePDF}
      disabled={isGenerating}
      className={`group relative flex items-center justify-center gap-3 w-full px-6 py-4 rounded-2xl font-bold text-lg overflow-hidden transition-all duration-300 ${
        isGenerating 
          ? 'bg-gray-100 text-gray-500 cursor-not-allowed' 
          : 'bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 text-white shadow-xl shadow-indigo-500/30 hover:shadow-indigo-500/50 hover:-translate-y-1'
      }`}
    >
      {/* Shine effect */}
      <div className="absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/20 to-transparent group-hover:animate-[shimmer_1.5s_infinite]" />
      
      {isGenerating ? (
        <Loader className="animate-spin" size={24} />
      ) : (
        <Sparkles size={24} className="text-blue-200" />
      )}
      
      <span>{isGenerating ? "Synthesizing AI Proposal..." : "One-Click AI Impact Proposal"}</span>
    </button>
  );
}
